import { supabase } from '@/lib/supabase/client';
import type { Avis, Litige, Promotion, Reservation, Transaction, Wallet, WalletTransaction, PublicationPromotion } from '@/types/database';

export const sellerService = {
  async products(vendeurId: string) { const { data, error } = await supabase.from('promotions').select('*').eq('vendeur_id', vendeurId).order('created_at', { ascending: false }); if (error) throw error; return (data ?? []) as Promotion[]; },
  async product(vendeurId: string, id: string) { const { data, error } = await supabase.from('promotions').select('*').eq('vendeur_id', vendeurId).eq('id', id).single(); if (error) throw error; return data as Promotion; },
  async orders(vendeurId: string) { const { data, error } = await supabase.from('transactions').select('*, promotion:promotions(titre,photo_url,prix_promo), client:profiles!transactions_client_id_fkey(nom,telephone,email)').eq('vendeur_id', vendeurId).order('created_at', { ascending: false }); if (error) throw error; return (data ?? []) as Transaction[]; },
  async order(vendeurId: string, id: string) { const { data, error } = await supabase.from('transactions').select('*, promotion:promotions(*), client:profiles!transactions_client_id_fkey(*), vendeur:profiles!transactions_vendeur_id_fkey(*)').eq('vendeur_id', vendeurId).eq('id', id).single(); if (error) throw error; return data as Transaction; },
  async reservations(vendeurId: string) { const { data, error } = await supabase.from('reservations').select('*, promotion:promotions(*), client:profiles!reservations_client_id_fkey(*)').eq('promotion.vendeur_id', vendeurId).order('created_at', { ascending: false }); if (error) throw error; return (data ?? []) as Reservation[]; },
  async reservation(vendeurId: string, id: string) { const { data, error } = await supabase.from('reservations').select('*, promotion:promotions(*), client:profiles!reservations_client_id_fkey(*)').eq('id', id).eq('promotion.vendeur_id', vendeurId).single(); if (error) throw error; return data as Reservation; },
  async wallet(vendeurId: string) { const { data, error } = await supabase.from('wallets').select('*').eq('user_id', vendeurId).maybeSingle(); if (error) throw error; return data as Wallet | null; },
  async walletTransactions(vendeurId: string) { const { data, error } = await supabase.from('wallet_transactions').select('*').eq('user_id', vendeurId).order('created_at', { ascending: false }).limit(100); if (error) throw error; return (data ?? []) as WalletTransaction[]; },
  async reviews(vendeurId: string) { const { data, error } = await supabase.from('avis').select('*, client:profiles!avis_client_id_fkey(nom)').eq('vendeur_id', vendeurId).order('created_at', { ascending: false }); if (error) throw error; return (data ?? []) as (Avis & { client?: { nom: string } })[]; },
  async disputes(vendeurId: string) { const { data, error } = await supabase.from('litiges').select('*, promotion:promotions(titre,photo_url), client:profiles!litiges_client_id_fkey(nom,telephone)').eq('promotion.vendeur_id', vendeurId).order('created_at', { ascending: false }); if (error) throw error; return (data ?? []) as (Litige & { promotion?: { titre: string; photo_url: string | null }; client?: { nom: string; telephone: string | null } })[]; },
  async campaigns(vendeurId: string) { const { data, error } = await supabase.from('publication_promotions').select('*, publication:promotions(titre,photo_url)').eq('vendeur_id', vendeurId).order('created_at', { ascending: false }); if (error) throw error; return (data ?? []) as PublicationPromotion[]; },
  async updateProduct(id: string, vendeurId: string, payload: Partial<Promotion>) { const { data, error } = await supabase.from('promotions').update(payload).eq('id', id).eq('vendeur_id', vendeurId).select().single(); if (error) throw error; return data as Promotion; },
  async shipOrder(id: string) { const { data, error } = await supabase.rpc('confirm_direct_shipped', { p_transaction_id: id }); if (error) throw error; return data; },
  async extendShipping(id: string) { const { data, error } = await supabase.rpc('extend_direct_shipping', { p_transaction_id: id }); if (error) throw error; return data; },
  async acceptReservation(id: string) { const { data, error } = await supabase.rpc('accept_reservation', { p_reservation_id: id }); if (error) throw error; return data; },
  async rejectReservation(id: string) { const { data, error } = await supabase.rpc('reject_reservation', { p_reservation_id: id }); if (error) throw error; return data; },
  async shipReservation(id: string) { const { data, error } = await supabase.rpc('mark_reservation_shipped', { p_reservation_id: id }); if (error) throw error; return data; },
};
