'use client';
import { useEffect, useState } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { AlertTriangle, ArrowUpRight, CheckCircle2, Clock3, Package, ReceiptText, ShieldCheck, ShoppingBag, Store, Users, WalletCards } from 'lucide-react';
import { supabase } from '@/lib/supabase/client';
import { useAuth } from '@/hooks/useAuth';
import { LoadingSpinner } from '@/components/ui/LoadingSpinner';

export default function AdminPage() {
  const { profile, loading } = useAuth(); const router = useRouter(); const [s, setS] = useState<any>(null);
  useEffect(() => { if (loading) return; if (profile?.role !== 'admin') { router.replace('/'); return; } (async () => { const [u,p,t,l,k] = await Promise.all([supabase.from('profiles').select('id',{count:'exact',head:true}),supabase.from('promotions').select('id',{count:'exact',head:true}),supabase.from('transactions').select('id,montant_total',{count:'exact'}),supabase.from('litiges').select('id',{count:'exact',head:true}).eq('statut','ouvert'),supabase.from('kyc_submissions').select('id',{count:'exact',head:true}).eq('status','en_attente')]); const total=(t.data||[]).reduce((a,x)=>a+Number(x.montant_total||0),0); setS({users:u.count||0,products:p.count||0,transactions:t.count||0,volume:total,disputes:l.count||0,kyc:k.count||0}); })(); }, [loading, profile, router]);
  if (loading || !s) return <main className='min-h-screen bg-black flex items-center justify-center'><LoadingSpinner/></main>;
  const cards=[['Utilisateurs',s.users,Users,'/admin/utilisateurs'],['Vendeurs',s.users,Store,'/admin/vendeurs'],['Publications',s.products,Package,'/admin/publications'],['Transactions',s.transactions,ReceiptText,'/admin/transactions'],['Litiges ouverts',s.disputes,AlertTriangle,'/admin/litiges'],['KYC en attente',s.kyc,ShieldCheck,'/admin/kyc']];
  return <main className='min-h-screen bg-black p-4 text-white sm:p-8'><div className='mx-auto max-w-7xl'><div className='flex flex-col justify-between gap-4 sm:flex-row'><div><p className='font-black tracking-widest text-orange-500'>PROMO’S WORLD</p><h1 className='mt-2 text-3xl font-black'>Centre de contrôle</h1><p className='mt-1 text-zinc-500'>Pilotage opérationnel de la marketplace.</p></div><Link href='/promo' className='flex items-center gap-2 self-start rounded-xl border border-white/10 px-4 py-3 text-sm font-bold hover:border-orange-500/50'>Voir le marketplace <ArrowUpRight size={16}/></Link></div><div className='mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-6'>{cards.map(([l,v,I,h]:any)=><Link key={l} href={h} className='rounded-2xl border border-white/10 bg-zinc-950 p-5 hover:border-orange-500/50'><I size={19} className='text-orange-500'/><p className='mt-5 text-xs font-semibold text-zinc-500'>{l}</p><p className='mt-1 text-2xl font-black'>{v}</p></Link>)}</div><div className='mt-6 grid gap-4 md:grid-cols-2'><section className='rounded-2xl border border-white/10 bg-zinc-950 p-6'><div className='flex items-center gap-2'><WalletCards size={19} className='text-orange-500'/><h2 className='font-black'>Volume cumulé</h2></div><p className='mt-3 text-3xl font-black text-orange-500'>{s.volume.toLocaleString()} FCFA</p><p className='mt-1 text-sm text-zinc-500'>Montant total des transactions enregistrées.</p></section><section className='rounded-2xl border border-white/10 bg-zinc-950 p-6'><div className='flex items-center gap-2'><Clock3 size={19} className='text-orange-500'/><h2 className='font-black'>À traiter maintenant</h2></div><div className='mt-4 flex flex-wrap gap-3 text-sm'><Link href='/admin/litiges' className='rounded-xl bg-white/5 px-3 py-2'>{s.disputes} litige(s)</Link><Link href='/admin/kyc' className='rounded-xl bg-white/5 px-3 py-2'>{s.kyc} KYC</Link></div><p className='mt-4 flex items-center gap-2 text-xs text-zinc-500'><CheckCircle2 size={14}/> Les actions sensibles doivent rester auditées côté serveur.</p></section></div></div></main>;
}
