"use client";

import Link from "next/link";
import { useMemo } from "react";
import { ArrowRight, BookOpen, Megaphone, Package, Sparkles, TrendingUp, UserRound } from "lucide-react";
import { useAuth } from "@/hooks/useAuth";
import { useLanguage } from "@/hooks/useLanguage";
import { usePromotions } from "@/hooks/usePromotions";
import { PromotionCard } from "@/components/promotion/PromotionCard";
import { LoadingSpinner } from "@/components/ui/LoadingSpinner";

const greetings:any={
 fr:{guestTitle:"Les bonnes affaires, en toute simplicité.",guestText:"Découvrez des articles et promotions, puis créez votre compte pour profiter de toute l'expérience.",market:"Découvrir le marketplace",join:"Créer un compte",how:"Comment ça marche ?",more:"Voir plus",featured:"En vedette dans votre ville",trending:"Les publications qui attirent l'attention",empty:"Les meilleures publications arriveront bientôt."},
 en:{guestTitle:"Great deals, made simple.",guestText:"Discover products and offers, then create your account to unlock the full experience.",market:"Explore marketplace",join:"Create an account",how:"How it works",more:"See more",featured:"Featured in your city",trending:"Listings getting attention",empty:"The best listings are coming soon."}
};
function dailyGreeting(name:string,role:string,lang:string){
 const frClient=[`${name}, quel article vous intéresse aujourd'hui ?`,`${name}, prêt à découvrir de nouvelles trouvailles ?`,`${name}, de bonnes affaires vous attendent aujourd'hui.`];
 const frSeller=[`${name}, on publie une nouvelle offre aujourd'hui ?`,`${name}, prêt à donner plus de visibilité à vos articles ?`,`${name}, votre marketplace vous attend.`];
 const enClient=[`${name}, what are you looking for today?`,`${name}, ready to discover something new?`,`${name}, great deals are waiting for you today.`];
 const enSeller=[`${name}, publishing a new offer today?`,`${name}, ready to give your products more visibility?`,`${name}, your marketplace is waiting for you.`];
 const list=lang==="en"?(role==="vendeur"?enSeller:enClient):(role==="vendeur"?frSeller:frClient);
 return list[new Date().getDate()%list.length];
}
export default function HomePage(){
 const {user,profile,loading:authLoading}=useAuth(); const {language}=useLanguage(); const {promotions,loading}=usePromotions(); const t=greetings[language];
 const local=useMemo(()=>[...promotions].sort((a:any,b:any)=>((b.ville===profile?.ville?3:0)+(b.pays===profile?.pays?1:0))-((a.ville===profile?.ville?3:0)+(a.pays===profile?.pays?1:0))),[promotions,profile]);
 const promoted=local.filter((p:any)=>p.is_promoted||p.promoted_until).slice(0,6); const trending=local.filter((p:any)=>!promoted.some((x:any)=>x.id===p.id)).slice(0,6);
 if(authLoading) return <main className="min-h-screen bg-black flex items-center justify-center"><LoadingSpinner/></main>;
 if(!user) return <main className="min-h-screen bg-black text-white"><section className="relative overflow-hidden border-b border-white/10"><div className="absolute inset-0 bg-[radial-gradient(circle_at_top_right,rgba(249,115,22,.25),transparent_35%)]"/><div className="relative mx-auto max-w-7xl px-5 py-24 sm:px-8 sm:py-32"><div className="max-w-3xl"><div className="inline-flex items-center gap-2 rounded-full border border-orange-500/30 bg-orange-500/10 px-4 py-2 text-orange-400"><Sparkles size={16}/>PROMO'S WORLD</div><h1 className="mt-7 text-5xl font-black leading-tight sm:text-7xl">{t.guestTitle}</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-zinc-400">{t.guestText}</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><Link href="/promo" className="rounded-xl bg-orange-500 px-6 py-4 text-center font-black text-black">{t.market}</Link><Link href="/comment-ca-marche" className="rounded-xl border border-orange-500/40 bg-orange-500/10 px-6 py-4 text-center font-bold text-orange-300"><BookOpen className="mr-2 inline" size={18}/>{t.how}</Link><Link href="/auth" className="rounded-xl border border-white/15 px-6 py-4 text-center font-bold">{t.join}</Link></div></div></div></section></main>;
 const name=profile?.nom||user.email?.split("@")[0]||"";
 return <main className="min-h-screen bg-black text-white px-4 py-7 sm:px-6 lg:px-10"><div className="mx-auto max-w-7xl"><section className="rounded-3xl border border-white/10 bg-gradient-to-br from-zinc-950 via-zinc-950 to-orange-500/10 p-7 sm:p-10"><div className="flex items-start gap-4"><div className="rounded-2xl bg-orange-500 p-3 text-black"><UserRound/></div><div><p className="text-sm font-bold text-orange-500">PROMO'S WORLD</p><h1 className="mt-2 text-3xl font-black sm:text-5xl">{dailyGreeting(name,profile?.role||"client",language)}</h1><p className="mt-3 text-zinc-400">{profile?.role==="vendeur"?(language==="en"?"Manage your listings, performance and visibility from one place.":"Gérez vos publications, vos performances et votre visibilité depuis un seul espace."):(language==="en"?"Discover listings prioritised for your location.":"Découvrez en priorité les publications proches de votre zone.")}</p></div></div><div className="mt-7 flex flex-wrap gap-3">{profile?.role==="vendeur"&&<><Link href="/dashboard" className="rounded-xl bg-orange-500 px-5 py-3 font-bold text-black">{language==="en"?"My dashboard":"Mon dashboard"}</Link><Link href="/publier" className="rounded-xl border border-white/10 px-5 py-3 font-bold">{language==="en"?"Publish":"Publier"}</Link></>}<Link href="/promo" className="rounded-xl border border-white/10 px-5 py-3 font-bold">{t.market} <ArrowRight className="inline" size={17}/></Link><Link href="/comment-ca-marche" className="rounded-xl border border-orange-500/30 bg-orange-500/10 px-5 py-3 font-bold text-orange-300">{t.how}</Link></div></section>
 {promoted.length>0&&<section className="mt-10"><div className="mb-5 flex items-end justify-between"><div><div className="flex items-center gap-2 text-orange-500"><Megaphone size={18}/><p className="text-sm font-bold uppercase tracking-wide">{t.featured}</p></div><h2 className="mt-2 text-2xl font-black">{language==="en"?"Sponsored for more visibility":"Mis en avant pour plus de visibilité"}</h2></div><Link href="/promo" className="text-sm text-orange-400">{t.more} →</Link></div><div className="flex gap-4 overflow-x-auto pb-3">{promoted.map((p:any)=><div key={p.id} className="min-w-[280px] max-w-[320px] flex-1"><PromotionCard promotion={p}/></div>)}</div></section>}
 <section className="mt-10"><div className="mb-5 flex items-end justify-between"><div><div className="flex items-center gap-2 text-orange-500"><TrendingUp size={18}/><p className="text-sm font-bold uppercase tracking-wide">{t.trending}</p></div><h2 className="mt-2 text-2xl font-black">{language==="en"?"Trending listings":"Articles et promotions en vogue"}</h2></div><Link href="/promo" className="text-sm text-orange-400">{t.more} →</Link></div>{loading?<div className="py-16 flex justify-center"><LoadingSpinner/></div>:trending.length?<div className="grid gap-5 sm:grid-cols-2 xl:grid-cols-3">{trending.map((p:any)=><PromotionCard key={p.id} promotion={p}/>)}</div>:<div className="rounded-3xl border border-dashed border-white/10 p-12 text-center text-zinc-500"><Package className="mx-auto mb-4"/>{t.empty}</div>}</section></div></main>;
}