"use client";

import Link from "next/link";
import { ArrowRight, BadgeCheck, MessageCircle, Search, ShieldCheck, ShoppingBag, Sparkles, Star, Wallet } from "lucide-react";
import { useLanguage } from "@/hooks/useLanguage";

export default function HomePage() {
  const { language } = useLanguage();
  const tr = language === "en" ? {
    badge:"Marketplace • Reservations • Secure transactions", title:"Good deals,", accent:"made simple.", intro:"Promo's World helps you discover products and promotions, reserve them and follow your transactions in a modern, intuitive experience.", explore:"Explore the marketplace", account:"Create an account", simple:"Simple experience", reviews:"User reviews", all:"Everything in one place", marketplace:"Marketplace", marketDesc:"Products and special offers", transactions:"Transactions", transDesc:"Follow your payments", reservations:"Reservations", reserveDesc:"Keep products aside", messages:"Messages", msgDesc:"Talk with sellers", section:"A COMPLETE EXPERIENCE", heading:"Designed to be easy to use.", how:"How does it work?", ready:"Ready to discover great deals?", readyText:"Join Promo's World and enjoy a modern experience to discover, buy, sell and reserve.", start:"Get started",
    features:[[Search,"Find products and offers","Discover interesting products and special offers quickly."],[ShieldCheck,"Shop with confidence","A clear journey to buy, reserve, track and confirm transactions."],[Wallet,"Stay in control","Track your wallet, movements and transactions in one place."],[MessageCircle,"Communicate easily","Talk directly with buyers and sellers when you need to."]],
    steps:[["01","Discover","Browse products and promotions available on the marketplace."],["02","Choose","Buy directly or reserve the product you want."],["03","Track","Follow every stage of your transaction."]]
  } : {
    badge:"Marketplace • Réservations • Transactions sécurisées", title:"Les bonnes affaires,", accent:"en toute simplicité.", intro:"Promo's World vous permet de découvrir des articles et des promotions, de les réserver et de suivre vos transactions dans une expérience moderne et intuitive.", explore:"Découvrir le marketplace", account:"Créer un compte", simple:"Expérience simplifiée", reviews:"Avis utilisateurs", all:"Tout au même endroit", marketplace:"Marketplace", marketDesc:"Articles et offres spéciales", transactions:"Transactions", transDesc:"Suivez vos paiements", reservations:"Réservations", reserveDesc:"Gardez vos produits de côté", messages:"Messages", msgDesc:"Échangez avec les vendeurs", section:"UNE EXPÉRIENCE COMPLÈTE", heading:"Pensée pour être simple à utiliser.", how:"Comment ça fonctionne ?", ready:"Prêt à découvrir les bonnes affaires ?", readyText:"Rejoignez Promo's World et profitez d'une expérience moderne pour découvrir, acheter, vendre et réserver.", start:"Commencer maintenant",
    features:[[Search,"Trouvez des articles et des offres","Découvrez rapidement des produits intéressants et des offres spéciales."],[ShieldCheck,"Achetez avec confiance","Un parcours clair pour acheter, réserver, suivre et confirmer vos transactions."],[Wallet,"Gardez le contrôle","Suivez votre portefeuille, vos mouvements et vos transactions depuis un seul espace."],[MessageCircle,"Communiquez facilement","Échangez directement avec les vendeurs et les clients lorsque nécessaire."]],
    steps:[["01","Découvrez","Parcourez les articles et promotions disponibles sur le marketplace."],["02","Choisissez","Achetez directement ou réservez le produit qui vous intéresse."],["03","Suivez","Gardez un œil sur chaque étape de votre transaction."]]
  };
  const modules=[["🔥",tr.marketplace,tr.marketDesc],["💳",tr.transactions,tr.transDesc],["📦",tr.reservations,tr.reserveDesc],["💬",tr.messages,tr.msgDesc]];
  return <main className="min-h-screen bg-black text-white">
    <section className="relative overflow-hidden border-b border-white/10"><div className="absolute inset-0 bg-[radial-gradient(circle_at_top_right,rgba(249,115,22,0.22),transparent_32%),radial-gradient(circle_at_left,rgba(249,115,22,0.10),transparent_28%)]"/><div className="relative mx-auto grid max-w-7xl gap-12 px-4 py-20 sm:px-6 sm:py-28 lg:grid-cols-2 lg:items-center lg:px-8"><div><div className="mb-6 inline-flex items-center gap-2 rounded-full border border-orange-500/30 bg-orange-500/10 px-4 py-2 text-sm text-orange-400"><Sparkles size={16}/>{tr.badge}</div><h1 className="text-4xl font-black leading-tight sm:text-5xl lg:text-6xl">{tr.title}<span className="block text-orange-500">{tr.accent}</span></h1><p className="mt-6 max-w-2xl text-base leading-7 text-zinc-400 sm:text-lg">{tr.intro}</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link href="/promo" className="inline-flex items-center justify-center gap-2 rounded-xl bg-orange-500 px-6 py-3.5 font-bold text-black"><ShoppingBag size={19}/>{tr.explore}<ArrowRight size={18}/></Link><Link href="/auth" className="inline-flex items-center justify-center rounded-xl border border-white/15 px-6 py-3.5 font-semibold">{tr.account}</Link></div><div className="mt-10 flex flex-wrap gap-5 text-sm text-zinc-400"><span className="flex items-center gap-2"><BadgeCheck className="text-orange-500" size={18}/>{tr.simple}</span><span className="flex items-center gap-2"><Star className="text-orange-500" size={18}/>{tr.reviews}</span></div></div><div className="rounded-3xl border border-white/10 bg-zinc-950 p-5 shadow-2xl sm:p-7"><p className="text-sm text-zinc-500">Promo's World</p><h2 className="mb-5 text-xl font-bold">{tr.all}</h2><div className="space-y-3">{modules.map(([emoji,title,description])=><div key={title} className="flex items-center gap-4 rounded-2xl border border-white/5 bg-white/[0.03] p-4"><div className="text-2xl">{emoji}</div><div><p className="font-semibold">{title}</p><p className="text-sm text-zinc-500">{description}</p></div></div>)}</div></div></div></section>
    <section className="mx-auto max-w-7xl px-4 py-20 sm:px-6 lg:px-8"><p className="text-sm font-bold uppercase tracking-wider text-orange-500">{tr.section}</p><h2 className="mt-3 text-3xl font-black sm:text-4xl">{tr.heading}</h2><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{tr.features.map(([Icon,title,description]:any)=><article key={title} className="rounded-2xl border border-white/10 bg-zinc-950 p-6"><div className="mb-5 inline-flex rounded-xl bg-orange-500/10 p-3 text-orange-500"><Icon size={23}/></div><h3 className="font-bold">{title}</h3><p className="mt-3 text-sm leading-6 text-zinc-500">{description}</p></article>)}</div></section>
    <section className="border-y border-white/10 bg-zinc-950/50"><div className="mx-auto max-w-7xl px-4 py-20 sm:px-6 lg:px-8"><h2 className="text-center text-3xl font-black">{tr.how}</h2><div className="mt-12 grid gap-5 md:grid-cols-3">{tr.steps.map(([number,title,description])=><div key={number} className="rounded-2xl border border-white/10 bg-black p-6"><span className="text-4xl font-black text-orange-500/70">{number}</span><h3 className="mt-6 text-xl font-bold">{title}</h3><p className="mt-2 text-sm leading-6 text-zinc-500">{description}</p></div>)}</div></div></section>
    <section className="mx-auto max-w-5xl px-4 py-20 text-center sm:px-6"><div className="rounded-3xl border border-orange-500/20 bg-gradient-to-br from-orange-500/15 to-transparent p-8 sm:p-12"><h2 className="text-3xl font-black sm:text-4xl">{tr.ready}</h2><p className="mx-auto mt-4 max-w-xl text-zinc-400">{tr.readyText}</p><Link href="/promo" className="mt-7 inline-flex items-center gap-2 rounded-xl bg-orange-500 px-7 py-3.5 font-bold text-black">{tr.start}<ArrowRight size={18}/></Link></div></section>
  </main>;
}
